language: clojure
dist: xenial
lein: lein
jdk:
  - openjdk8
  ## can't install on xenial
  #  - oraclejdk8
  - openjdk11
  - oraclejdk11
before_script:
  - bash ./bin/ci/before_script.sh
script:
  - lein do clean, cloverage --codecov
after_success:
  - bash <(curl -s https://codecov.io/bash)
before_deploy:
  ## TODO: different profiles
  - lein with-profile prod ring uberjar
#  - lein with-profile github-release ring uberjar
deploy:
  ## TODO: different providers
#  - provider: releases
#    api_key: $GITHUB_TOKEN
#    skip_cleanup: true
#    file_glob: true
#    on:
#      tags: true
#    ## TODO: uberjar path
#    file: "target/uberjar/*-standalone.jar"

